### ISSUE TITLE
Add GitHub link in docs

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/targ#21]
Now we have moved to the Piccolo Theme, we can add a link to GitHub in the nav bar of the docs.

To do this, just follow [these docs](https://piccolo-theme.readthedocs.io/en/latest/configuration.html#source-url), and change `conf.py` accordingly, so it links to `https://github.com/piccolo-orm/targ/`.

Approximate time needed: 20 minutes.

**Comment by rk-1620** [comment]
I want to work. Please assign it to me.

**Comment by dantownsend** [comment]
@rk-1620 Cool, thanks!

**Comment by Krish-Paul** [comment]
Please assign this to me. This is my 1st attempt at hacktoberfest.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/targ/pull/22

**Comment by dantownsend** [comment]
@Krish-Paul I'll have a think in case there is another issue I can create for you.
