### ISSUE TITLE
Please bump up dependancy versions

### ISSUE THREAD

**Issue by arunkumar-pt** [piccolo-orm/targ#26]
Unable to install "piccolo" with "fastkafka" since one of the dependencies went into version conflict. Please update dependency versions. If you have suggestions, pls let me know.

<img width="934" alt="Screenshot 2023-03-23 at 7 02 46 PM" src="https://user-images.githubusercontent.com/122965916/227220466-c7629adc-7eaf-46b4-8906-13c1ad074ce0.png">

Thank you.

**Comment by dantownsend** [comment]
Try again now - `targ==0.3.8` should fix it.

**Comment by arunkumar-pt** [comment]
Thanks. It worked.
